Documentation:
  Enabled: false

LineLength:
  Max: 999

AllCops:
  RunRailsCops: true
  Include:
    - Gemfile
    - lib/tasks/*
  Exclude:
    - db/schema.rb
    - db/migrations
    - vendor/bundle
    - bin/**/*
